@TestOn('browser')
library test.unit.browser.generated_runner_test;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/browser -e Environment.browser --no-genHtml`

import './json_schema/validation_test.dart' as json_schema_validation_test;
import 'package:test/test.dart';

void main() {
  json_schema_validation_test.main();
}